version: '3'
services:
  payments-service:
    build: "./payments-service"
    depends_on:
      - payments-service-db
    environment:
      - DB_URI=mysql://root:password@payments-service-db/db?charset=UTF8
    volumes:
      - ./payments-service:/opt/app
    networks:
      - rmnet

  payments-service-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 0.0.0.0:7200:3306
    cap_add:
      - SYS_NICE
    networks:
      - rmnet

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    environment:
      - DB_URI=mysql://root:password@users-service-db/db?charset=UTF8
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:8.0
    ports:
      - 0.0.0.0:7201:3306
    cap_add:
      - SYS_NICE

  expenses-service:
    build: "./expenses-service"
    depends_on:
      - expenses-service-db
    environment:
      - DB_URI=mysql://root:password@expenses-service-db/db?charset=UTF8
    volumes:
      - ./expenses-service:/opt/app

  expenses-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:8.0
    ports:
      - 0.0.0.0:7202:3306
    cap_add:
      - SYS_NICE

networks:
  rmnet:
    driver: bridge